export const dummyVoteList = [
  {
    id: 1,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    likeNum: 3,
    dislikeNum: 1,
  },
  {
    id: 2,
    originalTitle: '날씨',
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    dislikeNum: 3,
  },
  {
    id: 1,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    likeNum: 3,
    dislikeNum: 1,
  },
  {
    id: 2,
    originalTitle: '날씨',
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    dislikeNum: 3,
  },
  {
    originalTitle: '날씨',
    id: 1,
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    likeNum: 3,
    dislikeNum: 1,
  },
  {
    id: 2,
    originalTitle: '날씨',
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    dislikeNum: 3,
  },
  {
    id: 1,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    likeNum: 3,
    dislikeNum: 1,
  },
  {
    id: 2,
    originalTitle: '날씨',
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    dislikeNum: 3,
  },
  {
    id: 1,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    likeNum: 3,
    dislikeNum: 1,
  },
  {
    originalTitle: '날씨',
    id: 2,
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    dislikeNum: 3,
  },
];

export const dummyDebateList = [
  {
    id: 1,
    originalTitle: '끝',
    title: '끝난토론 예시1',
    username: '독수리타법 7남매1',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 3,
  },
  {
    id: 2,
    originalTitle: '난',
    title: '끝난토론 에시2',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    commentNum: 3,
  },
  {
    id: 3,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 3. 11:23',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 4,
  },
  {
    id: 4,
    originalTitle: '날씨',
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 12. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    commentNum: 4,
  },
  {
    id: 5,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 13. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 4,
  },
  {
    id: 6,
    originalTitle: '날씨',
    title: '오늘의 날씨는 궁금하지가 않습니다',
    username: '여행갈고양',
    time: '2024. 01. 15. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    commentNum: 3,
  },
  {
    id: 7,
    originalTitle: '날씨',
    title: '마리모는 식물이 아니라 동물입니다',
    username: '독수리타법 7남매',
    time: '2024. 01. 12. 01:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 4,
  },
  {
    id: 8,
    originalTitle: 'java',
    title: '이 부분은 오타인 것 같습니다',
    username: '여행갈고양',
    time: '2024. 01. 20. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    commentNum: 4,
  },
  {
    id: 9,
    originalTitle: 'javascript',
    title: '클로저 부분에서 잘못된 서술이 있습니다.',
    username: '독수리타법 7남매',
    time: '2024. 02. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 4,
  },
  {
    id: 10,
    originalTitle: 'typescript',
    title: '타입스크립트에서 타입 지정을 다음과 같이 수정하고 싶습니다',
    username: '여행갈고양',
    time: '2024. 02. 10. 10:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    commentNum: 4,
  },
  {
    id: 11,
    originalTitle: 'dfs',
    title: 'dfs는 이렇게 구현하면 안됩니다',
    username: '독수리타법 7남매',
    time: '2024. 04. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 4,
  },
  {
    id: 12,
    originalTitle: '날씨',
    title: '날씨가 이렇게 맑다니!',
    username: '여행갈고양',
    time: '2025. 02. 10. 10:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    commentNum: 4,
  },
];

export const dummyEndDebateList = [
  {
    id: 1,
    originalTitle: '끝',
    title: '끝난토론 예시1',
    username: '독수리타법 7남매1',
    time: '2024. 01. 10. 11:38',
    content:
      '마리모는 동물입니다. 동물을 식물이라고 부르는 것은 마리모에게 실례입니다.',
    commentNum: 3,
  },
  {
    id: 2,
    originalTitle: '난',
    title: '끝난토론 에시2',
    username: '여행갈고양',
    time: '2024. 01. 10. 11:22',
    content: '여행갈 때에는 오늘의 날씨가 중요하긴 합니다. 그러나',
    likeNum: 22,
    dislikeNum: 3,
    commentNum: 3,
  },
];
